### ISSUE TITLE
theater view mode icon reflects wrong mode on startup

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-games/toolbox#22]

**Comment by PaulAroo** [comment]
didn't think I should leave a PR cause it a small tweak
maybe I should???

here is the [commit](https://github.com/benevolent-games/toolbox/compare/master...xui) that fixes the bug

**Comment by chase-moskal** [comment]
@PaulAroo there's absolutely nothing wrong with launching a PR, even for a one-line tweak

keeping a tiny fix like this, in its own branch, with its own PR, actually helps us keep track of what's getting done, when, and where.

generally speaking, it's worse when developers "smuggle" small work into unrelated branches/PRs

**Comment by PaulAroo** [comment]
Okay then
I'll launch a PR
