### ISSUE TITLE
rewrite the spectator cam

### ISSUE THREAD

**Issue by chase-moskal** [benevolent-games/toolbox#26]

**Comment by PaulAroo** [comment]
@zenkyuv , in this refactor, maybe allow the `makeSpectatorCamera` function accept a default camera starting position as one of it's arguments

**Comment by zenkyuv** [comment]
> @zenkyuv , in this refactor, maybe allow the `makeSpectatorCamera` function accept a default camera starting position as one of it's arguments

maybe i should add this yeah
